export default [
  { name: 'git status allowed', prompts: ['hello'], tool: 'Bash', command: 'git status', expect: 'allow' },
  { name: 'git log allowed', prompts: ['hello'], tool: 'Bash', command: 'git log --oneline -5', expect: 'allow' },
  { name: 'git -C diff allowed', prompts: ['hello'], tool: 'Bash', command: 'git -C /x diff', expect: 'allow' },
  { name: 'git status; git log allowed', prompts: ['hello'], tool: 'Bash', command: 'git status; git log', expect: 'allow' },
  { name: 'git log piped to head allowed', prompts: ['hello'], tool: 'Bash', command: 'git log | head', expect: 'allow' },
  { name: 'git status piped to grep for the word git allowed', prompts: ['hello'], tool: 'Bash', command: 'git status | grep git', expect: 'allow' },
  { name: 'git commit denied without instruction', prompts: ['hello'], tool: 'Bash', command: 'git commit -m x', expect: 'deny' },
  { name: 'git commit allowed when prompt names commit', prompts: ['commit this'], tool: 'Bash', command: 'git commit -m x', expect: 'allow' },
  { name: 'instruction does not survive next prompt', prompts: ['commit this', 'hello'], tool: 'Bash', command: 'git commit -m x', expect: 'deny' },
  { name: 'mixed read-only plus commit denied', prompts: ['hello'], tool: 'Bash', command: 'git status && git commit -m x', expect: 'deny' },
  { name: 'cd then git add denied', prompts: ['hello'], tool: 'Bash', command: 'cd /tmp && git add -A', expect: 'deny' },
  { name: 'git checkout denied', prompts: ['hello'], tool: 'Bash', command: 'git checkout main', expect: 'deny' },
  { name: 'env prefix git push denied', prompts: ['hello'], tool: 'Bash', command: 'FOO=1 git push', expect: 'deny' },
  { name: 'command substitution git push denied', prompts: ['hello'], tool: 'Bash', command: 'echo $(git push)', expect: 'deny' },
  { name: 'absolute path git commit denied', prompts: ['hello'], tool: 'Bash', command: '/usr/bin/git commit -m x', expect: 'deny' },
  { name: 'sudo git commit denied', prompts: ['hello'], tool: 'Bash', command: 'sudo git commit -m x', expect: 'deny' },
  { name: 'MACHINIST main session push allowed', prompts: ['hello'], agentType: 'MACHINIST', tool: 'Bash', command: 'git push', expect: 'allow' },
  { name: 'MACHINIST main session pull allowed', prompts: ['hello'], agentType: 'MACHINIST', tool: 'Bash', command: 'git pull', expect: 'allow' },
  { name: 'MACHINIST main session commit denied', prompts: ['hello'], agentType: 'MACHINIST', tool: 'Bash', command: 'git commit -m x', expect: 'deny' },
  { name: 'non-MACHINIST push denied', prompts: ['hello'], agentType: '', tool: 'Bash', command: 'git push', expect: 'deny' },
  { name: 'subagent of MACHINIST push denied', prompts: ['hello'], agentType: 'MACHINIST', subagent: true, tool: 'Bash', command: 'git push', expect: 'deny' },
  { name: 'plain command allowed', prompts: ['hello'], tool: 'Bash', command: 'echo hi', expect: 'allow' },
  { name: 'grep for the word git allowed', prompts: ['hello'], tool: 'Bash', command: 'ls | grep git', expect: 'allow' },
  { name: 'echo with git push in quotes allowed', prompts: ['hello'], tool: 'Bash', command: 'echo "run git push later"', expect: 'allow' },
  { name: 'sed -i denied', prompts: ['hello'], tool: 'Bash', command: "sed -i '' 's/a/b/' f", expect: 'deny' },
  { name: 'perl -pi denied', prompts: ['hello'], tool: 'Bash', command: "perl -pi -e 's/a/b/' f", expect: 'deny' },
  { name: 'awk -i inplace denied', prompts: ['hello'], tool: 'Bash', command: "awk -i inplace '{print}' f", expect: 'deny' },
  { name: 'sudo sed -i denied', prompts: ['hello'], tool: 'Bash', command: 'sudo sed -i s/a/b/ f', expect: 'deny' },
  { name: 'xargs sed -i denied', prompts: ['hello'], tool: 'Bash', command: 'ls | xargs sed -i s/a/b/', expect: 'deny' },
  { name: 'find -exec sed -i denied', prompts: ['hello'], tool: 'Bash', command: 'find . -name x -exec sed -i s/a/b/ {} ;', expect: 'deny' },
  { name: 'sed -n allowed', prompts: ['hello'], tool: 'Bash', command: 'sed -n 1p f', expect: 'allow' },
  { name: 'sed to stdout allowed', prompts: ['hello'], tool: 'Bash', command: "sed -e 's/a/b/' f > g", expect: 'allow' },
  { name: 'echo of sed -i text allowed', prompts: ['hello'], tool: 'Bash', command: 'echo sed -i is blocked', expect: 'allow' },
  { name: 'agent right model allowed', prompts: ['hello'], tool: 'Agent', subagentType: 'Pathfinder', model: 'haiku', expect: 'allow' },
  { name: 'agent lowercase type right model allowed', prompts: ['hello'], tool: 'Agent', subagentType: 'pathfinder', model: 'haiku', expect: 'allow' },
  { name: 'agent wrong model denied', prompts: ['hello'], tool: 'Agent', subagentType: 'Pathfinder', model: 'opus', expect: 'deny' },
  { name: 'agent missing model denied', prompts: ['hello'], tool: 'Agent', subagentType: 'Pathfinder', expect: 'deny' },
  { name: 'agent engineer sonnet allowed', prompts: ['hello'], tool: 'Agent', subagentType: 'Engineer', model: 'sonnet', expect: 'allow' },
  { name: 'agent auditor fable allowed', prompts: ['hello'], tool: 'Agent', subagentType: 'Auditor', model: 'fable', expect: 'allow' },
  { name: 'agent without definition allowed', prompts: ['hello'], tool: 'Agent', subagentType: 'general-purpose', expect: 'allow' },
  { name: 'no-gate COUNSELOR AskUserQuestion denied', prompts: ['no gate'], role: 'COUNSELOR', tool: 'AskUserQuestion', expect: 'deny' },
  { name: 'no-gate hyphen EnterPlanMode denied', prompts: ['do it, no-gate'], role: 'COUNSELOR', tool: 'EnterPlanMode', expect: 'deny' },
  { name: 'ordinary prompt AskUserQuestion allowed', prompts: ['go ahead'], role: 'COUNSELOR', tool: 'AskUserQuestion', expect: 'allow' },
  { name: 'no-gate MACHINIST AskUserQuestion allowed', prompts: ['no gate'], role: 'MACHINIST', tool: 'AskUserQuestion', expect: 'allow' },
  { name: 'no-gate role from role file MACHINIST allowed', prompts: ['no gate'], roleFile: 'MACHINIST', tool: 'AskUserQuestion', expect: 'allow' },
  { name: 'no-gate empty role file defaults to COUNSELOR denied', prompts: ['no gate'], roleFile: '', tool: 'AskUserQuestion', expect: 'deny' },
  { name: 'no-gate COUNSELOR Bash allowed', prompts: ['no gate'], role: 'COUNSELOR', tool: 'Bash', command: 'echo hi', expect: 'allow' },
  { name: 'no-gate disarmed by next prompt', prompts: ['no gate', 'ok'], role: 'COUNSELOR', tool: 'AskUserQuestion', expect: 'allow' },
  { name: 'nudge absent on 4th prompt, read directive present', prompts: ['a', 'b', 'c', 'd'], role: 'MACHINIST', tool: 'Bash', command: 'echo hi', expect: 'allow', contextLinesOnLastPrompt: 1 },
  { name: 'nudge present on 5th prompt, with read directive', prompts: ['a', 'b', 'c', 'd', 'e'], role: 'MACHINIST', tool: 'Bash', command: 'echo hi', expect: 'allow', contextLinesOnLastPrompt: 2 },
  { name: 'read directive present on 1st prompt for ORACLE', prompts: ['a'], role: 'ORACLE', tool: 'Bash', command: 'echo hi', expect: 'allow', contextLinesOnLastPrompt: 1 },
]
